# Generated by Django 6.1.1 on 2026-09-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('opportunity_type', models.CharField(choices=[('Internship', 'Internship'), ('Job', 'Job'), ('Hackathon', 'Hackathon'), ('Course', 'Course'), ('Workshop', 'Workshop'), ('Other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('required_skills', models.CharField(help_text='Example: Python, Django, SQL', max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('application_link', models.URLField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
