# Generated by Django 6.1.1 on 2026-09-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='organization',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='application_link',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='title',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='locations',
            field=models.CharField(blank=True, help_text='Example: Chennai, Bengaluru, Hyderabad, Remote', max_length=300),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='official_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='relevant_careers',
            field=models.CharField(blank=True, help_text='Example: Python Developer, Full Stack Developer', max_length=500),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='relevant_skills',
            field=models.CharField(blank=True, help_text='Example: Python, Django, SQL, Git', max_length=500),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Job', 'Job'), ('Graduate', 'Graduate'), ('Multiple', 'Multiple')], max_length=30),
        ),
    ]
